services:
  postgres:
    image: postgres:18.1
    container_name: payload_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: